services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # local directory to container directory
    stdin_open: true # As FastAPI is interactive, this is needed
    environment:
      - ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Avoid overwriting node_modules
    stdin_open: true # As React is interactive, this is needed